# Install Homebrew packages
---
- name: Checking if Homebrew is installed
  stat:
    path: /opt/homebrew/bin/brew
  register: brew_check


- when: brew_check.stat.exists
  block:
  - name: Updating Homebrew
    homebrew:
      update_homebrew: true

  - name: Tapping Homebrew Repositories
    homebrew_tap:
      name: "{{ homebrew_taps }}"
      state: present
    register: result
    until: result is successful

  - name: Installing Homebrew Cask Packages
    homebrew_cask:
      name: "{{ cask_packages }}"
      state: present
    register: result
    until: result is successful

  - name: Installing Homebrew Packages
    homebrew:
      name: "{{ brew_packages }}"
      state: present
    register: result
    until: result is successful

