# Clone dotfiles from github 
---
- name: Checking if dotfiles repository is present
  stat:
    path: ~/dotfiles
  register: dot_check

- name: Cloning dotfiles repository
  git:
    repo: 'https://github.com/Jose-N/dotfiles'
    dest: ~/dotfiles
  when:
    - not dot_check.stat.exists

