# Copy zshrc from dotfiles
---
- name: Checking if dotfiles repository is present
  stat:
    path: ~/dotfiles
  register: dot_check

- when: dot_check.stat.exists
  block:
  - name: Updating dotfiles repository
    git:
      repo: 'https://github.com/Jose-N/dotfiles'
      dest: ~/dotfiles
      update: true

  - name: Removing existing zshrc
    shell: rm ~/.zshrc
    ignore_errors: true

  - name: Copying zshrc
    shell: cp ~/dotfiles/.zshrc ~/.zshrc

  - name: source zshrc
    shell: source ~/.zshrc
