# Copy .p10k.conf from dotfiles
---
- name: Checking if dotfiles repository is present
  stat:
    path: ~/dotfiles
  register: dot_check

- when: dot_check.stat.exists
  block:
  - name: Updating dotfiles repository
    git:
      repo: 'https://github.com/Jose-N/dotfiles'
      dest: ~/dotfiles
      update: true

  - name: Removing existing powerlevel10k settings
    shell: rm ~/.p10k.zsh
    ignore_errors: true

  - name: Copying powerlevel10k settings
    shell: cp ~/dotfiles/.p10k.zsh ~/.p10k.zsh
