# Copy lazyvim config from dotfiles
---
- name: Checking if dotfiles repository is present
  stat:
    path: ~/dotfiles
  register: dot_check

- when: dot_check.stat.exists
  block:
  - name: Updating dotfiles repository
    git:
      repo: 'https://github.com/Jose-N/dotfiles'
      dest: ~/dotfiles
      update: true

  - name: Creating .config dir
    shell: mkdir ~/.config
    ignore_errors: true

  - name: Removing existing nvim settings
    shell: rm -rf ~/.config/nvim
    ignore_errors: true

  - name: Deleting lazyvim config
    shell: rm -rf ~/.config/nvim 
    ignore_errors: true

  - name: Copying lazyvim config
    shell: cp -r ~/dotfiles/nvim ~/.config/
