# Copy .tmux.conf from dotfiles
---
- name: Checking if dotfiles repository is present
  stat:
    path: ~/dotfiles
  register: dot_check

- when: dot_check.stat.exists
  block:
  - name: Updating dotfiles repository
    git:
      repo: 'https://github.com/Jose-N/dotfiles'
      dest: ~/dotfiles
      update: true

  - name: Removing existing tmux.conf
    shell: rm ~/.tmux.conf
    ignore_errors: true

  - name: Copying tmux.conf
    shell: cp ~/dotfiles/.tmux.conf ~/.tmux.conf
