# Set iterm2 to use config in dotfiles
---
- name: Checking if dotfiles repository is present
  stat:
    path: ~/dotfiles
  register: dot_check

- when: dot_check.stat.exists
  block:
  - name: Updating dotfiles repository
    git:
      repo: 'https://github.com/Jose-N/dotfiles'
      dest: ~/dotfiles
      update: true

  - name: Specifying iterm2 settings dir
    shell: defaults write com.googlecode.iterm2 PrefsCustomFolder -string "~/dotfiles/iterm2"

  - name: Enabling iterm2 external settings
    shell: defaults write com.googlecode.iterm2 LoadPrefsFromCustomFolder -bool true
