---
- name: Configure Go
  hosts: mac
  become: false
  tasks:
    - name: Checking if goenv folder exists
      stat:
        path: ~/.goenv
      register: goenv_check

    - name: Installing Go via goenv
      shell: /opt/homebrew/bin/goenv install latest
      when:
        - not goenv_check.stat.exists

    - name: Setting global go version
      shell:  /opt/homebrew/bin/goenv global `/opt/homebrew/bin/goenv versions`
      when:
        - not goenv_check.stat.exists

    - name: Installing delve
      shell: /opt/homebrew/bin/goenv exec go install github.com/go-delve/delve/cmd/dlv@latest

    - name: Installing templ
      shell: /opt/homebrew/bin/goenv exec go install github.com/a-h/templ/cmd/templ@latest

    - name: Installing air
      shell: /opt/homebrew/bin/goenv exec go install github.com/air-verse/air@latest
