---
- name: Install oh-my-zsh and themes
  hosts: mac
  become: false
  tasks:
    - name: Ensuring oh-my-zsh is installed
      stat:
        path: ~/.oh-my-zsh
      register: omz_check

    - name: Installing oh-my-zsh
      shell: /bin/bash sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
      when:
        - not omz_check.stat.exists
